---
abstract: 'Compile Local::TextDomain language files'
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  Capture::Tiny: 0
  Module::Build: 0.35
  Test::DZil: 0
  Test::More: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.35
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-LocaleTextDomain
requires:
  Carp: 0
  Dist::Zilla::File::FromCode: 0
  Dist::Zilla::Role::FileGatherer: 0
  File::Path: 2.07
  IPC::Cmd: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/theory/dist-zilla-localetextdomain.git
version: 0.10
